require:
  - rubocop-performance
  - 'test_prof/rubocop'
  - rubocop-rspec
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
