require:
  - rubocop-performance
  - "test_prof/rubocop"
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
