name: linters
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      - run: |
          bundle exec rubocop --color --parallel --fail-level E
          bundle exec brakeman -q -w3 -i brakeman.ignore
